[package]
name = "voice-pitch-feedback"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
publish = false
description = "A voice app that changes pitch for biofeedback practice"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oxifft = { version = "0.3.0", features = ["signal"] }
eframe = "0.29.1"
realtime-tools = { workspace = true }

[target.'cfg(windows)'.dependencies]
neo-audio = { workspace = true, default-features = false, features = ["processors", "rtaudio-backend"] }

[target.'cfg(not(windows))'.dependencies]
neo-audio = { workspace = true, default-features = false, features = ["processors", "portaudio-backend"] }


[package.metadata.bundle]
icon = ["icon.png"]
identifier = "io.github.elstickelsSlp.voicePitchFeedback"
